"use client"

import { Shield } from "lucide-react"
import { LegalDocumentPage, type LocalizedLegalContent } from "@/components/legal-document-page"
import { useLanguage } from "@/components/language-provider"

const localizedContent: LocalizedLegalContent = {
  en: { effectiveDate: "January 8, 2025", sections: [{ title: "1. Company Identification", blocks: [{ type: "list", items: ["Legal name: SN SOLUTIONS LLC.", "Trade name: SN WHITE HOSTING.", "EIN: 32-0817400.", "Registered address: 1209 Mountain Road Pl NE, Ste N, Albuquerque, New Mexico, 87110, USA."] }] }, { title: "2. Domain Services", blocks: [{ type: "paragraph", text: "SN WHITE HOSTING provides domain-related services as an independent hosting and domain provider working with different accredited registrars depending on the TLD and service involved." }] }, { title: "3. Contact Information", blocks: [{ type: "list", items: ["Official website: www.snwhitehosting.com.", "Support contact: support@snwhitehosting.com.", "Abuse contact: abuse@snwhitehosting.com.", "Legal contact: legal@snwhitehosting.com."] }] }, { title: "4. Transparency and Compliance", blocks: [{ type: "list", items: ["Domain operations are subject to ICANN policies and the rules of each applicable registry.", "Customers may be subject to registrar- or registry-specific obligations depending on the selected TLD.", "SN WHITE HOSTING aims to provide transparent information about the authorities and contractual framework applicable to each domain service."] }] }] },
  es: { effectiveDate: "8 de enero de 2025", sections: [{ title: "1. Identificación de la Empresa", blocks: [{ type: "list", items: ["Denominación legal: SN SOLUTIONS LLC.", "Nombre comercial: SN WHITE HOSTING.", "EIN: 32-0817400.", "Domicilio registrado: 1209 Mountain Road Pl NE, Ste N, Albuquerque, New Mexico, 87110, USA."] }] }, { title: "2. Servicios de Dominios", blocks: [{ type: "paragraph", text: "SN WHITE HOSTING presta servicios relacionados con dominios como proveedor independiente de hosting y dominios, trabajando con distintos registradores acreditados según el TLD y el servicio implicado." }] }, { title: "3. Información de Contacto", blocks: [{ type: "list", items: ["Sitio web oficial: www.snwhitehosting.com.", "Contacto de soporte: support@snwhitehosting.com.", "Contacto de abusos: abuse@snwhitehosting.com.", "Contacto legal: legal@snwhitehosting.com."] }] }, { title: "4. Transparencia y Cumplimiento", blocks: [{ type: "list", items: ["Las operaciones de dominios están sujetas a las políticas de ICANN y a las reglas de cada registro aplicable.", "Los clientes pueden quedar sujetos a obligaciones específicas del registrador o del registro según el TLD seleccionado.", "SN WHITE HOSTING procura ofrecer información transparente sobre las autoridades y el marco contractual aplicable a cada servicio de dominio."] }] }] },
  de: { effectiveDate: "8. Januar 2025", sections: [{ title: "1. Unternehmensidentifikation", blocks: [{ type: "list", items: ["Rechtlicher Name: SN SOLUTIONS LLC.", "Handelsname: SN WHITE HOSTING.", "EIN: 32-0817400.", "Registrierte Anschrift: 1209 Mountain Road Pl NE, Ste N, Albuquerque, New Mexico, 87110, USA."] }] }, { title: "2. Domain-Dienste", blocks: [{ type: "paragraph", text: "SN WHITE HOSTING erbringt domainbezogene Dienste als unabhängiger Hosting- und Domainanbieter und arbeitet je nach TLD und Dienst mit verschiedenen akkreditierten Registraren zusammen." }] }, { title: "3. Kontaktinformationen", blocks: [{ type: "list", items: ["Offizielle Website: www.snwhitehosting.com.", "Support-Kontakt: support@snwhitehosting.com.", "Abuse-Kontakt: abuse@snwhitehosting.com.", "Rechtskontakt: legal@snwhitehosting.com."] }] }, { title: "4. Transparenz und Compliance", blocks: [{ type: "list", items: ["Domainvorgänge unterliegen den ICANN-Richtlinien und den Regeln der jeweils zuständigen Registry.", "Je nach gewählter TLD können Kunden zusätzlichen registrar- oder registryspezifischen Pflichten unterliegen.", "SN WHITE HOSTING bemüht sich um transparente Informationen über die zuständigen Stellen und den vertraglichen Rahmen jedes Domain-Dienstes."] }] }] },
  nl: { effectiveDate: "8 januari 2025", sections: [{ title: "1. Identificatie van de Onderneming", blocks: [{ type: "list", items: ["Juridische naam: SN SOLUTIONS LLC.", "Handelsnaam: SN WHITE HOSTING.", "EIN: 32-0817400.", "Geregistreerd adres: 1209 Mountain Road Pl NE, Ste N, Albuquerque, New Mexico, 87110, USA."] }] }, { title: "2. Domeindiensten", blocks: [{ type: "paragraph", text: "SN WHITE HOSTING levert domeingerelateerde diensten als onafhankelijke hosting- en domeinprovider en werkt afhankelijk van de TLD en de betrokken dienst samen met verschillende geaccrediteerde registrars." }] }, { title: "3. Contactinformatie", blocks: [{ type: "list", items: ["Officiële website: www.snwhitehosting.com.", "Supportcontact: support@snwhitehosting.com.", "Misbruikcontact: abuse@snwhitehosting.com.", "Juridisch contact: legal@snwhitehosting.com."] }] }, { title: "4. Transparantie en Compliance", blocks: [{ type: "list", items: ["Domeinactiviteiten zijn onderworpen aan ICANN-beleid en de regels van elke toepasselijke registry.", "Klanten kunnen afhankelijk van de gekozen TLD onderworpen zijn aan specifieke verplichtingen van registrar of registry.", "SN WHITE HOSTING streeft naar transparante informatie over de bevoegde instanties en het contractuele kader dat voor elke domeindienst geldt."] }] }] },
}

export default function RegistrarInformationPage() {
  const { t } = useLanguage()

  return <LegalDocumentPage icon={Shield} title={t.legal.registrarInfoTitle} subtitle={t.legal.registrarInfoSubtitle} currentPath="/registrar-information" content={localizedContent} />
}