// Game server plans data from clients.snwhitehosting.com
// All prices in USD (monthly unless specified otherwise)

export interface GamePlan {
  name: string
  priceUSD: number
  features: string[]
  ram?: string
  cores?: string
  storage?: string
  link: string
}

export const gamePlans = {
  minecraftJava: [
    {
      name: "Free Server",
      priceUSD: 0,
      features: ["2GB RAM", "2 Cores", "5GB Storage", "Pterodactyl Panel", "All Versions", "Unlimited Slots", "Plugins", "Mods", "Database", "FTP", "24/7 Support"],
      ram: "2GB",
      cores: "2",
      storage: "5GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/minecraft-servers",
    },
    {
      name: "Wood Plan",
      priceUSD: 6.00,
      features: ["2GB RAM", "2 Cores", "5GB Storage", "Pterodactyl Panel", "All Versions", "Unlimited Slots", "Plugins", "Mods", "Database", "FTP", "24/7 Support"],
      ram: "2GB",
      cores: "2",
      storage: "5GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/minecraft-servers",
    },
    {
      name: "Stone Plan",
      priceUSD: 9.00,
      features: ["3GB RAM", "2 Cores", "8GB Storage", "Pterodactyl Panel", "All Versions", "Unlimited Slots", "Plugins", "Mods", "Database", "FTP", "24/7 Support"],
      ram: "3GB",
      cores: "2",
      storage: "8GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/minecraft-servers",
    },
    {
      name: "Iron Plan",
      priceUSD: 14.00,
      features: ["4GB RAM", "2 Cores", "10GB Storage", "Pterodactyl Panel", "All Versions", "Unlimited Slots", "Plugins", "Mods", "Database", "FTP", "24/7 Support"],
      ram: "4GB",
      cores: "2",
      storage: "10GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/minecraft-servers",
    },
    {
      name: "Gold Plan",
      priceUSD: 20.00,
      features: ["6GB RAM", "4 Cores", "20GB Storage", "Pterodactyl Panel", "All Versions", "Unlimited Slots", "Plugins", "Mods", "Database", "FTP", "24/7 Support"],
      ram: "6GB",
      cores: "4",
      storage: "20GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/minecraft-servers",
    },
    {
      name: "Copper Plan",
      priceUSD: 25.00,
      features: ["8GB RAM", "4 Cores", "50GB Storage", "Pterodactyl Panel", "All Versions", "Unlimited Slots", "Plugins", "Mods", "Database", "FTP", "24/7 Support"],
      ram: "8GB",
      cores: "4",
      storage: "50GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/minecraft-servers",
    },
    {
      name: "Diamond Plan",
      priceUSD: 35.00,
      features: ["12GB RAM", "6 Cores", "50GB Storage", "Pterodactyl Panel", "All Versions", "Unlimited Slots", "Plugins", "Mods", "Database", "FTP", "24/7 Support"],
      ram: "12GB",
      cores: "6",
      storage: "50GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/minecraft-servers",
    },
  ],
  minecraftBedrock: [
    {
      name: "Free Server",
      priceUSD: 0,
      features: ["1GB RAM", "1 Core", "5GB Storage", "Pterodactyl Panel", "All Versions", "Unlimited Slots", "Plugins", "Mods", "Database", "FTP", "24/7 Support"],
      ram: "1GB",
      cores: "1",
      storage: "5GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/minecraf-bedrock-servers",
    },
    {
      name: "Wood Plan",
      priceUSD: 6.00,
      features: ["2GB RAM", "2 Cores", "5GB Storage", "Pterodactyl Panel", "All Versions", "Unlimited Slots", "Plugins", "Mods", "Database", "FTP", "24/7 Support"],
      ram: "2GB",
      cores: "2",
      storage: "5GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/minecraf-bedrock-servers",
    },
    {
      name: "Stone Plan",
      priceUSD: 9.00,
      features: ["3GB RAM", "2 Cores", "8GB Storage", "Pterodactyl Panel", "All Versions", "Unlimited Slots", "Plugins", "Mods", "Database", "FTP", "24/7 Support"],
      ram: "3GB",
      cores: "2",
      storage: "8GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/minecraf-bedrock-servers",
    },
    {
      name: "Iron Plan",
      priceUSD: 14.00,
      features: ["4GB RAM", "2 Cores", "10GB Storage", "Pterodactyl Panel", "All Versions", "Unlimited Slots", "Plugins", "Mods", "Database", "FTP", "24/7 Support"],
      ram: "4GB",
      cores: "2",
      storage: "10GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/minecraf-bedrock-servers",
    },
    {
      name: "Gold Plan",
      priceUSD: 20.00,
      features: ["6GB RAM", "4 Cores", "20GB Storage", "Pterodactyl Panel", "All Versions", "Unlimited Slots", "Plugins", "Mods", "Database", "FTP", "24/7 Support"],
      ram: "6GB",
      cores: "4",
      storage: "20GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/minecraf-bedrock-servers",
    },
    {
      name: "Copper Plan",
      priceUSD: 25.00,
      features: ["8GB RAM", "4 Cores", "50GB Storage", "Pterodactyl Panel", "All Versions", "Unlimited Slots", "Plugins", "Mods", "Database", "FTP", "24/7 Support"],
      ram: "8GB",
      cores: "4",
      storage: "50GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/minecraf-bedrock-servers",
    },
    {
      name: "Diamond Plan",
      priceUSD: 35.00,
      features: ["12GB RAM", "6 Cores", "50GB Storage", "Pterodactyl Panel", "All Versions", "Unlimited Slots", "Plugins", "Mods", "Database", "FTP", "24/7 Support"],
      ram: "12GB",
      cores: "6",
      storage: "50GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/minecraf-bedrock-servers",
    },
  ],
  terraria: [
    {
      name: "Free Server",
      priceUSD: 0,
      features: ["512MB RAM", "1 Core", "5GB Storage", "Pterodactyl Panel", "Unlimited Slots", "Mods", "Plugins", "Database", "FTP", "24/7 Support"],
      ram: "512MB",
      cores: "1",
      storage: "5GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/terraria",
    },
    {
      name: "Rare Loot Plan",
      priceUSD: 3.00,
      features: ["2GB RAM", "1 Core", "5GB Storage", "Pterodactyl Panel", "Unlimited Slots", "Mods", "Plugins", "Database", "FTP", "24/7 Support"],
      ram: "2GB",
      cores: "1",
      storage: "5GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/terraria",
    },
    {
      name: "Treasure Plan",
      priceUSD: 4.00,
      features: ["3GB RAM", "1 Core", "8GB Storage", "Pterodactyl Panel", "Unlimited Slots", "Mods", "Plugins", "Database", "FTP", "24/7 Support"],
      ram: "3GB",
      cores: "1",
      storage: "8GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/terraria",
    },
    {
      name: "Pure Magic Plan",
      priceUSD: 6.00,
      features: ["4GB RAM", "2 Cores", "15GB Storage", "Pterodactyl Panel", "Unlimited Slots", "Mods", "Plugins", "Database", "FTP", "24/7 Support"],
      ram: "4GB",
      cores: "2",
      storage: "15GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/terraria",
    },
  ],
  projectZomboid: [
    {
      name: "Free Server",
      priceUSD: 0,
      features: ["3GB RAM", "2 Cores", "5GB Storage", "Pterodactyl Panel", "Unlimited Slots", "Mods", "Database", "FTP", "24/7 Support"],
      ram: "3GB",
      cores: "2",
      storage: "5GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/project-zomboid",
    },
    {
      name: "Disaster Start Plan",
      priceUSD: 2.35,
      features: ["2GB RAM", "2 Cores", "5GB Storage", "Pterodactyl Panel", "Unlimited Slots", "Mods", "Database", "FTP", "24/7 Support"],
      ram: "2GB",
      cores: "2",
      storage: "5GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/project-zomboid",
    },
    {
      name: "Virus T Plan",
      priceUSD: 5.00,
      features: ["4GB RAM", "2 Cores", "8GB Storage", "Pterodactyl Panel", "Unlimited Slots", "Mods", "Database", "FTP", "24/7 Support"],
      ram: "4GB",
      cores: "2",
      storage: "8GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/project-zomboid",
    },
    {
      name: "No Survivor Plan",
      priceUSD: 9.30,
      features: ["6GB RAM", "3 Cores", "10GB Storage", "Pterodactyl Panel", "Unlimited Slots", "Mods", "Database", "FTP", "24/7 Support"],
      ram: "6GB",
      cores: "3",
      storage: "10GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/project-zomboid",
    },
    {
      name: "Winter Disaster Plan",
      priceUSD: 18.75,
      features: ["10GB RAM", "4 Cores", "15GB Storage", "Pterodactyl Panel", "Unlimited Slots", "Mods", "Database", "FTP", "24/7 Support"],
      ram: "10GB",
      cores: "4",
      storage: "15GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/project-zomboid",
    },
  ],
  hytale: [
    {
      name: "Common Plan",
      priceUSD: 7.00,
      features: ["2.5GB RAM", "2 Cores", "10GB Storage", "Pterodactyl Panel", "Unlimited Slots", "Plugins", "Mods", "Database", "FTP", "Backups", "24/7 Support"],
      ram: "2.5GB",
      cores: "2",
      storage: "10GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/hytale",
    },
    {
      name: "Rare Plan",
      priceUSD: 11.00,
      features: ["4GB RAM", "2 Cores", "15GB Storage", "Pterodactyl Panel", "Unlimited Slots", "Plugins", "Mods", "Database", "FTP", "Backups", "24/7 Support"],
      ram: "4GB",
      cores: "2",
      storage: "15GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/hytale",
    },
    {
      name: "Epic Plan",
      priceUSD: 16.00,
      features: ["6GB RAM", "2 Cores", "20GB Storage", "Pterodactyl Panel", "Unlimited Slots", "Plugins", "Mods", "2 Databases", "FTP", "Backups", "24/7 Support"],
      ram: "6GB",
      cores: "2",
      storage: "20GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/hytale",
    },
    {
      name: "Legendary Plan",
      priceUSD: 20.00,
      features: ["8GB RAM", "3 Cores", "20GB Storage", "Pterodactyl Panel", "Unlimited Slots", "Plugins", "Mods", "2 Databases", "FTP", "Backups", "24/7 Support"],
      ram: "8GB",
      cores: "3",
      storage: "20GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/hytale",
    },
    {
      name: "Boss Plan",
      priceUSD: 30.00,
      features: ["12GB RAM", "3 Cores", "50GB Storage", "Pterodactyl Panel", "Unlimited Slots", "Plugins", "Mods", "3 Databases", "FTP", "Backups", "24/7 Support"],
      ram: "12GB",
      cores: "3",
      storage: "50GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/hytale",
    },
  ],
  fivem: [
    {
      name: "Mini Performance Plan",
      priceUSD: 18.00,
      features: ["6GB RAM", "4 Cores", "80GB Storage", "Pterodactyl Panel", "Database", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "6GB",
      cores: "4",
      storage: "80GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/five-m",
    },
    {
      name: "Regular Plan",
      priceUSD: 26.00,
      features: ["8GB RAM", "4 Cores", "128GB Storage", "Pterodactyl Panel", "2 Databases", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "8GB",
      cores: "4",
      storage: "128GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/five-m",
    },
    {
      name: "Performance Plan",
      priceUSD: 40.75,
      features: ["16GB RAM", "8 Cores", "256GB Storage", "Pterodactyl Panel", "2 Databases", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "16GB",
      cores: "8",
      storage: "256GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/five-m",
    },
  ],
  ragemp: [
    {
      name: "Spirited 300 Plan",
      priceUSD: 3.50,
      features: ["2GB RAM", "2 Cores", "32GB Storage", "Pterodactyl Panel", "Database", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "2GB",
      cores: "2",
      storage: "32GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/ragemp",
    },
    {
      name: "Sabre Turbo Plan",
      priceUSD: 7.00,
      features: ["4GB RAM", "2 Cores", "80GB Storage", "Pterodactyl Panel", "Database", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "4GB",
      cores: "2",
      storage: "80GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/ragemp",
    },
    {
      name: "Jester Classic Plan",
      priceUSD: 11.65,
      features: ["6GB RAM", "3 Cores", "80GB Storage", "Pterodactyl Panel", "2 Databases", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "6GB",
      cores: "3",
      storage: "80GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/ragemp",
    },
    {
      name: "Silver Plan",
      priceUSD: 17.45,
      features: ["8GB RAM", "4 Cores", "120GB Storage", "Pterodactyl Panel", "2 Databases", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "8GB",
      cores: "4",
      storage: "120GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/ragemp",
    },
    {
      name: "8F Drafter Plan",
      priceUSD: 25.61,
      features: ["12GB RAM", "6 Cores", "256GB Storage", "Pterodactyl Panel", "4 Databases", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "12GB",
      cores: "6",
      storage: "256GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/ragemp",
    },
    {
      name: "10F Wide Body Plan",
      priceUSD: 40.75,
      features: ["16GB RAM", "8 Cores", "256GB Storage", "Pterodactyl Panel", "4 Databases", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "16GB",
      cores: "8",
      storage: "256GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/ragemp",
    },
  ],
  samp: [
    {
      name: "Free Server",
      priceUSD: 0,
      features: ["1GB RAM", "1 Core", "5GB Storage", "Pterodactyl Panel", "Database", "Unlimited Slots", "24/7 Support"],
      ram: "1GB",
      cores: "1",
      storage: "5GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/samp",
    },
    {
      name: "Ryder Plan",
      priceUSD: 2.90,
      features: ["1GB RAM", "1 Core", "5GB Storage", "Pterodactyl Panel", "Database", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "1GB",
      cores: "1",
      storage: "5GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/samp",
    },
    {
      name: "Zero Plan",
      priceUSD: 5.82,
      features: ["2GB RAM", "1 Core", "8GB Storage", "Pterodactyl Panel", "Database", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "2GB",
      cores: "1",
      storage: "8GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/samp",
    },
    {
      name: "Sweet Plan",
      priceUSD: 9.35,
      features: ["3GB RAM", "2 Cores", "15GB Storage", "Pterodactyl Panel", "Database", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "3GB",
      cores: "2",
      storage: "15GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/samp",
    },
    {
      name: "Big Smoke Plan",
      priceUSD: 11.65,
      features: ["6GB RAM", "2 Cores", "20GB Storage", "Pterodactyl Panel", "2 Databases", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "6GB",
      cores: "2",
      storage: "20GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/samp",
    },
    {
      name: "Carl Johnson Plan",
      priceUSD: 17.45,
      features: ["8GB RAM", "3 Cores", "30GB Storage", "Pterodactyl Panel", "2 Databases", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "8GB",
      cores: "3",
      storage: "30GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/samp",
    },
  ],
  mtasa: [
    {
      name: "Free Server",
      priceUSD: 0,
      features: ["1GB RAM", "1 Core", "5GB Storage", "Pterodactyl Panel", "Database", "Unlimited Slots", "24/7 Support"],
      ram: "1GB",
      cores: "1",
      storage: "5GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/mtasa",
    },
    {
      name: "Palomino Creek Plan",
      priceUSD: 2.90,
      features: ["1GB RAM", "1 Core", "5GB Storage", "Pterodactyl Panel", "Database", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "1GB",
      cores: "1",
      storage: "5GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/mtasa",
    },
    {
      name: "Blueberry Plan",
      priceUSD: 5.82,
      features: ["2GB RAM", "1 Core", "8GB Storage", "Pterodactyl Panel", "Database", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "2GB",
      cores: "1",
      storage: "8GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/mtasa",
    },
    {
      name: "Las Venturas Plan",
      priceUSD: 9.35,
      features: ["3GB RAM", "2 Cores", "15GB Storage", "Pterodactyl Panel", "Database", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "3GB",
      cores: "2",
      storage: "15GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/mtasa",
    },
    {
      name: "San Fierro Plan",
      priceUSD: 11.65,
      features: ["6GB RAM", "2 Cores", "20GB Storage", "Pterodactyl Panel", "2 Databases", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "6GB",
      cores: "2",
      storage: "20GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/mtasa",
    },
    {
      name: "Los Santos Plan",
      priceUSD: 17.45,
      features: ["8GB RAM", "3 Cores", "30GB Storage", "Pterodactyl Panel", "2 Databases", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "8GB",
      cores: "3",
      storage: "30GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/mtasa",
    },
  ],
  americanTruck: [
    {
      name: "Free Server",
      priceUSD: 0,
      features: ["2GB RAM", "2 Cores", "20GB Storage", "Pterodactyl Panel", "Mods", "Database", "Unlimited Slots", "24/7 Support"],
      ram: "2GB",
      cores: "2",
      storage: "20GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/american",
    },
    {
      name: "New Mexico Plan",
      priceUSD: 6.00,
      features: ["2GB RAM", "2 Cores", "20GB Storage", "Pterodactyl Panel", "Mods", "Database", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "2GB",
      cores: "2",
      storage: "20GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/american",
    },
    {
      name: "Texas Plan",
      priceUSD: 9.30,
      features: ["3GB RAM", "2 Cores", "30GB Storage", "Pterodactyl Panel", "Mods", "Database", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "3GB",
      cores: "2",
      storage: "30GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/american",
    },
    {
      name: "Miami Plan",
      priceUSD: 13.00,
      features: ["4GB RAM", "3 Cores", "50GB Storage", "Pterodactyl Panel", "Mods", "Database", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "4GB",
      cores: "3",
      storage: "50GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/american",
    },
    {
      name: "Las Vegas Plan",
      priceUSD: 17.45,
      features: ["6GB RAM", "3 Cores", "80GB Storage", "Pterodactyl Panel", "Mods", "Database", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "6GB",
      cores: "3",
      storage: "80GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/american",
    },
  ],
  rust: [
    {
      name: "Scrap Plan",
      priceUSD: 16.40,
      features: ["6GB RAM", "4 Cores", "32GB Storage", "Pterodactyl Panel", "Mods", "Plugins", "Database", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "6GB",
      cores: "4",
      storage: "32GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/rust",
    },
    {
      name: "Sheet Metal Plan",
      priceUSD: 22.00,
      features: ["8GB RAM", "4 Cores", "64GB Storage", "Pterodactyl Panel", "Mods", "Plugins", "2 Databases", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "8GB",
      cores: "4",
      storage: "64GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/rust",
    },
    {
      name: "Metal Plate Plan",
      priceUSD: 28.00,
      features: ["10GB RAM", "6 Cores", "128GB Storage", "Pterodactyl Panel", "Mods", "Plugins", "3 Databases", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "10GB",
      cores: "6",
      storage: "128GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/rust",
    },
    {
      name: "Gear Plan",
      priceUSD: 34.00,
      features: ["12GB RAM", "6 Cores", "256GB Storage", "Pterodactyl Panel", "Mods", "Plugins", "4 Databases", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "12GB",
      cores: "6",
      storage: "256GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/rust",
    },
    {
      name: "Electric Fuse Plan",
      priceUSD: 40.75,
      features: ["16GB RAM", "8 Cores", "256GB Storage", "Pterodactyl Panel", "Mods", "Plugins", "4 Databases", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "16GB",
      cores: "8",
      storage: "256GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/rust",
    },
  ],
  assettoCom: [
    {
      name: "Rookie Plan",
      priceUSD: 9.00,
      features: ["3GB RAM", "2 Cores", "32GB Storage", "Pterodactyl Panel", "Mods", "Plugins", "Database", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "3GB",
      cores: "2",
      storage: "32GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/assetto-corsa",
    },
    {
      name: "Expert Pilot Plan",
      priceUSD: 25.00,
      features: ["8GB RAM", "4 Cores", "64GB Storage", "Pterodactyl Panel", "Mods", "Plugins", "2 Databases", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "8GB",
      cores: "4",
      storage: "64GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/assetto-corsa",
    },
    {
      name: "Engineer Plan",
      priceUSD: 35.00,
      features: ["12GB RAM", "6 Cores", "128GB Storage", "Pterodactyl Panel", "Mods", "Plugins", "2 Databases", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "12GB",
      cores: "6",
      storage: "128GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/assetto-corsa",
    },
  ],
  cs2: [
    {
      name: "Free Server",
      priceUSD: 0,
      features: ["2GB RAM", "2 Cores", "10GB Storage", "Pterodactyl Panel", "Mods", "Plugins", "Database", "Unlimited Slots", "24/7 Support"],
      ram: "2GB",
      cores: "2",
      storage: "10GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/counter",
    },
    {
      name: "Silver Plan",
      priceUSD: 6.00,
      features: ["2GB RAM", "2 Cores", "10GB Storage", "Pterodactyl Panel", "Mods", "Plugins", "Database", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "2GB",
      cores: "2",
      storage: "10GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/counter",
    },
    {
      name: "Fury Plan",
      priceUSD: 9.00,
      features: ["3GB RAM", "2 Cores", "20GB Storage", "Pterodactyl Panel", "Mods", "Plugins", "Database", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "3GB",
      cores: "2",
      storage: "20GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/counter",
    },
    {
      name: "Mouz Plan",
      priceUSD: 14.00,
      features: ["4GB RAM", "2 Cores", "50GB Storage", "Pterodactyl Panel", "Mods", "Plugins", "Database", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "4GB",
      cores: "2",
      storage: "50GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/counter",
    },
    {
      name: "9z Team Plan",
      priceUSD: 18.00,
      features: ["6GB RAM", "4 Cores", "64GB Storage", "Pterodactyl Panel", "Mods", "Plugins", "Database", "Unlimited Slots", "Backups", "24/7 Support"],
      ram: "6GB",
      cores: "4",
      storage: "64GB",
      link: "https://clients.snwhitehosting.com/index.php?rp=/store/counter",
    },
  ],
}
