CREATE TABLE IF NOT EXISTS global_settings (
  settings_key VARCHAR(64) NOT NULL PRIMARY KEY,
  settings_value JSON NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
